version: '3.5'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: ./data/postgres
    volumes:
      - postgres:$PWD/data/postgres
    ports:
      - "15432:5432"
    restart: unless-stopped
  kingpin:
    build: .
    image: kingpin:latest
    environment:
      DATABASE_URL: "ecto://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/kingpin_dev"
      SECRET_KEY_BASE: wAS0ruVI5SnxcQcx6R9e0vWIhAAZXN8f3I5jhvqzL9odQuwyyggDD4qpCizhWw4K
    ports:
      - "4000:4000"
    restart: unless-stopped

volumes:
  postgres:
