apiVersion: v1
kind: Pod
metadata:
  name: docker
  labels:
    name: docker
spec:
  containers:
  - name: docker
    image: docker:stable
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
