apiVersion: v1
kind: Pod
metadata:
  name: docker
  labels:
    name: docker
spec:
  serviceAccountName: ci-worker
  containers:
  - name: docker
    image: docker:19.03.8
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    tty: true
    command:
      - cat
    securityContext:
      privileged: true
    volumeMounts:
      - name: dockersocket
        mountPath: /var/run/docker.sock
      - name: dockercfg
        mountPath: /root/.docker
        readOnly: true
  - name: kubectl
    image: lachlanevenson/k8s-kubectl:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    tty: true
    command:
      - cat
  - name: busybox
    image: busybox:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    tty: true
    command:
      - cat
  volumes:
    - name: dockersocket
      hostPath:
        path: /var/run/docker.sock
    - name: dockercfg
      secret:
        secretName: internal-registry
        items:
          - key: .dockerconfigjson
            path: config.json
