version: '3.5'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-kingpin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: ./data/postgres
    volumes:
      - postgres:$PWD/data/postgres
    ports:
      - 15432:5432
    restart: unless-stopped
  kingpin:
    build: kingpin/
    image: kingpin:latest
    environment:
      POSTGRES_URL: postgres:5432
      POSTGRES_USER: ${POSTGRES_USER:-kingpin}
      POSTGRES_PW: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: kingpin
    ports:
      - 4000:4000
    restart: unless-stopped

volumes:
  postgres: