version: '3'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=https://backend
    ports:
      - '9000:9000'
    environment:
      - PORT=9000
      
volumes:
  db:
    driver: local
