version: '3'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - VPR_DB_USER=postgres
      - VPR_DB_PASS=postgres
      - VPR_DB_HOST=db
      - VPR_DB_PORT=5432
      - VPR_DB_NAME=postgres
      - VPR_FRONTEND_CORS_ORIGIN=http://localhost:3000
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=http://localhost:8080
    ports:
      - '9000:9000'
    environment:
      - PORT=9000
      
volumes:
  db:
    driver: local
