version: '3'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  backend:
    image: cosmtrek/air
    working_dir: /app
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app
  web:
    image: node:lts
    working_dir: /var/www/html/app
    entrypoint: npm run host
    environment:
      - VITE_API_BASE_URL=http://localhost:8080
    ports:
      - 3000:3000
    volumes:
      - ./web:/var/www/html/app
volumes:
  db:
    driver: local
