apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          envFrom:
            - secretRef:
                name: postgres-login
      securityContext:
        fsGroup: 2000
      volumes:
        - name: postgres-data
          emptyDir: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kingpin
spec:
  replicas: 2
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: kingpin
  template:
    metadata:
      labels:
        app: kingpin
    spec:
      containers:
        - name: kingpin
          image: KINGPIN_IMAGE
          ports:
            - containerPort: 4000
          env:
            - name: POSTGRES_URL
              value: postgres:5432
          envFrom:
            - secretRef:
                name: postgres-login
            - secretRef:
                name: secret-key
            - secretRef:
                name: google-oauth
          livenessProbe:
            httpGet:
              path: /api/health/check
              port: 4000
          readinessProbe:
            httpGet:
              path: /api/health/check
              port: 4000
      imagePullSecrets:
        - name: goblin-wrangler
