apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ci-server-home
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ci-server-config
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce