apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kingpin
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - KINGPIN_HOST
      secretName: kingpin-tls
  rules:
    - host: KINGPIN_HOST
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kingpin
                port:
                  name: app

---
apiVersion: v1
kind: Service
metadata:
  name: kingpin
spec:
  selector:
    app: kingpin
  ports:
   - name: app
     protocol: TCP
     port: 4000
     targetPort: 4000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kingpin
spec:
  replicas: 2
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: kingpin
  template:
    metadata:
      labels:
        app: kingpin
    spec:
      containers:
        - name: kingpin
          image: KINGPIN_IMAGE
          ports:
            - containerPort: 4000
          env:
            - name: POSTGRES_URL
              value: postgres:5432
          envFrom:
            - secretRef:
                name: postgres-login
            - secretRef:
                name: secret-key
            - secretRef:
                name: google-oauth
          livenessProbe:
            httpGet:
              path: /health/check
              port: 4000
          readinessProbe:
            httpGet:
              path: /health/check
              port: 4000
      imagePullSecrets:
        - name: goblin-wrangler
