apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
   - name: database
     protocol: TCP
     port: 5432
     targetPort: 5432

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-login
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          envFrom:
            - secretRef:
                name: postgres-login
          resources:
            requests:
              memory: 256m
              cpu: 500m
            limits:
              memory: 256m
              cpu: 500m
      securityContext:
        fsGroup: 2000
      volumes:
        - name: postgres-data
          emptyDir: {}
